language: node_js
before_install:
   - npm install @material-ui/core
   - npm install @material-ui/icons
node_js:
   - "stable"
cache:
   directories:
      - node_modules
script:
   - npm test
   - npm run build
on:
   branch: master
